//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNhaThuoc_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHDXuat
    {
        public string MaXuat { get; set; }
        public int MaKH { get; set; }
        public int MaHD { get; set; }
        public string MaThuoc { get; set; }
        public int SoLuong { get; set; }
        public Nullable<decimal> GiamGia { get; set; }
        public decimal TongTienThuoc { get; set; }
        public decimal Thue { get; set; }
        public System.DateTime ThoiGian { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual Thuoc Thuoc { get; set; }
    }
}
