//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNhaThuoc_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thuoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Thuoc()
        {
            this.CTHDNhap = new HashSet<CTHDNhap>();
            this.CTHDXuat = new HashSet<CTHDXuat>();
        }
    
        public string MaThuoc { get; set; }
        public string TenThuoc { get; set; }
        public string MaNhom { get; set; }
        public string NguonGoc { get; set; }
        public long MaNCC { get; set; }
        public long SoLuong { get; set; }
        public decimal GiaBan { get; set; }
        public string CachDung { get; set; }
        public System.DateTime HSD { get; set; }
        public string ChuY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHDNhap> CTHDNhap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHDXuat> CTHDXuat { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual NhomThuoc NhomThuoc { get; set; }
    }
}
